apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
      - name: nginx
        image: registry.redhat.io/ubi9/httpd-24
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
      volumes:
      - name: html-volume
        configMap:
          name: ""
